info:
  app:
    name: openapi-basic
    version: 1.0.0
    description:  openapi-basic

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
    
spring:
  profiles:
    active: prod
---
spring:
  profile: prod
  pid:
    file: /data/openapi-basic/run/openapi-basic.pid
  application:
    name: openapi-basic
logging:
  config: file:/data/openapi-basic/logback-prod.xml
log:
  file:
    path: "/data/openapi-basic/logs"

auth:
  authServer: "http://10.10.50.5:8080/v1/auth/basic/validate"
  appVersion: 1.0.0
rest:
  baseUrl: http://10.10.50.5:8080/v1/auth/basic/validate
  connectionTimeout: 10000
  readTimeout: 10000

server:
  port: 8082
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "/data/openapi-basic"
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

