info:
  app:
    name: openapi-extention
    version: 1.0.0
    description:  openapi-extention

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
    
spring:
  profiles:
    active: prod
---
spring:
  profile: prod
  pid:
    file: /data/openapi-extention/run/openapi-extention.pid
  application:
    name: openapi-extention
logging:
  config: file:/data/openapi-extention/logback-prod.xml
log:
  file:
    path: "/openapi-extention/logs"

auth:
  authServer: "http://10.10.50.5:8080/v2/auth/extention/validate"
  appVersion: 1.0.0
rest:
  connectionTimeout: 10000
  readTimeout: 10000

server:
  port: 8080
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "/data/openapi-extention"
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
