info:
  app:
    name: auth
    version: 0.0.1
    description:  auth

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
    
spring:
  profiles:
    active: prod
---
spring:
  profile: prod
  pid:
    file: /auth/run/auth.pid
  application:
    name: auth-server
  zipkin:
    baseUrl: http://${ZIPKIN_SERVER}:${ZIPKIN_PORT}
  sleuth:
    sampler:
      probability: 1.0
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:/auth/db/auth;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          format_sql: true
          show_sql: false
auth:
  appVersion: ${APPLICATION_VERSION}
  seed: 1234567890123456

logging:
  config: classpath:logback-prod.xml
log:
  file:
    path: "/auth/logs"
server:
  port: 28082
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "/auth"
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profile: local
  pid:
    file: C://dev/work/auth/run/auth.pid
  application:
    name: auth-server
  zipkin:
    baseUrl: http://10.10.50.2:9411
  sleuth:
    sampler:
      probability: 1.0
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:C://dev/work/auth/db/auth;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          format_sql: true
          show_sql: false
auth:
  appVersion: 1.0.0
  seed: 1234567890123456

logging:
  config: classpath:logback-local.xml
log:
  file:
    path: "C://dev/work/auth/logs"
server:
  port: 28082
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "/tmp/auth"
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profile: mac
  pid:
    file: /tmp/run/auth.pid
  application:
    name: auth-server
  zipkin:
    baseUrl: http://10.10.50.2:9411
  sleuth:
    sampler:
      probability: 1.0
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:/tmp/auth/db/auth;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          format_sql: true
          show_sql: false
auth:
  appVersion: 1.0.0
  seed: 1234567890123456

logging:
  config: classpath:logback-mac.xml
log:
  file:
    path: "/tmp/auth/logs"
server:
  port: 28082
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "/tmp/auth"
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true