info:
  app:
    name: openapi-pub
    version: 1.0.0
    description:  openapi-pub

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
    
spring:
  profiles:
    active: prod
---
spring:
  profile: prod
  pid:
    file: /data/openapi-pub/run/openapi-pub.pid
  application:
    name: openapi-pub
logging:
  config: classpath:logback-prod.xml
log:
  file:
    path: "/data/openapi-pub/logs"

auth:
  appVersion: 1.0.0
rest:
  connectionTimeout: 10000
  readTimeout: 10000

server:
  port: 28083
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "/data/openapi-pub"
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profile: local
  pid:
    file: C://dev/work/openapi-pub/run/openapi-pub.pid
  application:
    name: openapi-pub
logging:
  config: classpath:logback-local.xml
log:
  file:
    path: "C://dev/work/openapi-pub/logs"

auth:
  appVersion: 1.0.0
rest:
  connectionTimeout: 10000
  readTimeout: 10000

server:
  port: 28083
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "C://dev/work/openapi-pub"
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profile: mac
  pid:
    file: /tmp/openapi-pub/run/openapi-pub.pid
  application:
    name: openapi-run
logging:
  config: classpath:logback-mac.xml
log:
  file:
    path: "/tmp/openapi-pub/logs"

auth:
  appVersion: 1.0.0
rest:
  connectionTimeout: 10000
  readTimeout: 10000

server:
  port: 28083
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "/tmp/openapi-pub"
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
